spring.application.name=task-management-area-system
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=tams
spring.datasource.username=postgres
spring.datasource.password=admin